# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf

# Add any other personal Hyprland configuration below
#windowrule = workspace 5, match:class qemu
# Rule, Window Identifier

#Open Terminal floating and centered
#windowrule = float 1, match:class Alacritty
#windowrule = size 1400 900, match:class Alacritty
#windowrule = center 1, match:class Alacritty

# Detach Activity Monitor from floating-window preset and use a larger size
windowrule = tag -floating-window, match:class org.omarchy.btop
windowrule = float 1, match:class org.omarchy.btop
windowrule = center 1, match:class org.omarchy.btop
windowrule = size 1400 900, match:class org.omarchy.btop

#Detach About Page from floating window preset and use a larger size 
windowrule = tag -floating-window, match:class org.omarchy.bash
windowrule = float 1, match:class org.omarchy.bash
windowrule = center 1, match:class org.omarchy.bash
windowrule = size 1400 600, match:class org.omarchy.bash

#Open Spotify on workspace 3
windowrule = workspace 3, match:class Spotify

#Open Spotify-Player on workspace 3
windowrule = workspace 3, match:class spotify-tui
windowrule = float 1, match:class spotify-tui
windowrule = center 1, match:class spotify-tui
windowrule = size 1800 1200, match:class spotify-tui
